### ISSUE TITLE
Fails silently

### ISSUE THREAD

**Issue by jesperordrup** [gliderlabs/herokuish#1296] opened 2024-08-26 14:21 UTC
Im getting a "build failed" - no reason. 

Ive tried enabling NODE_VERBOSE=true which leads to no futher info.

Any pointers? 
Can you hint were to look further? 

version: gliderlabs/herokuish:latest
ubuntu: 22.04
docker: latest
dokku: latest

```
Pushing to Dokku Host
remote: -----> Cleaning up...        
remote: -----> Building memberservice from gliderlabs/herokuish:latest        
remote: -----> Adding BUILD_ENV to build environment...        
remote:        BUILD_ENV added successfully        
remote:        -----> Node.js app detected        
remote:                
remote: -----> Creating runtime environment        
remote:                
remote:        NPM_CONFIG_LOGLEVEL=error        
remote:        NODE_VERBOSE=false        
remote:        NODE_ENV=development        
remote:        NODE_MODULES_CACHE=true        
remote:                
remote: -----> Installing binaries        
remote:        engines.node (package.json):   15.14.x        
remote:        engines.npm (package.json):    unspecified (use default)        
remote:                
remote:        Resolving node version 15.14.x...        
remote:        Downloading and installing node 15.14.0...        
remote:                
remote: -----> Build failed        
```

**Comment by jesperordrup** [comment] 2024-08-26 14:26
For  a briev moment this comment was added to this issue:

![image](https://github.com/user-attachments/assets/06104d52-2798-4fcb-80a7-0a48de68ee1d)

I looks like something I should not click on.

**Comment by josegonzalez** [comment] 2024-08-27 04:18
Yeah probably github spam :(

Regardless, I'm assuming you are using Dokku. Mind enabling trace mode on your deploy and displaying the output from a resulting release?

**Comment by josegonzalez** [comment] 2024-08-27 04:57
Closing this as it is a duplicate of dokku/dokku#7080 and its better tracked there as tests pass here.

**Closed by josegonzalez** 2024-08-27 04:57 UTC
