### ISSUE TITLE
Building app with PHP buildpack issue

### ISSUE THREAD

**Issue by danabrey** [gliderlabs/herokuish#529] opened 2020-02-29 09:49 UTC
I'm experiencing an issue when trying to deploy my PHP applications on Dokku, related to not being able to find the mbstring extension when using the PHP buildpack: https://github.com/heroku/heroku-buildpack-php

The issue is the same as explained here: https://github.com/heroku/heroku-buildpack-php/issues/395

```
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-php
=====> Detected Framework: PHP
-----> Bootstrapping...
-----> Installing platform packages...
       - php (7.4.3)
       - ext-mbstring (bundled with php)
       - apache (2.4.41)
       - nginx (1.16.1)
PHP Warning:  PHP Startup: Unable to load dynamic library 'mbstring.so' (tried: /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so (libonig.so.4: cannot open shared object file: No such file or directory), /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so.so (/app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'mbstring.so' (tried: /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so (libonig.so.4: cannot open shared object file: No such file or directory), /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so.so (/app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
-----> Installing dependencies...
       Composer version 1.9.3 2020-02-04 12:58:49
       PHP Warning:  PHP Startup: Unable to load dynamic library 'mbstring.so' (tried: /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so (libonig.so.4: cannot open shared object file: No such file or directory), /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so.so (/app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
       Loading composer repositories with package information
       Installing dependencies from lock file
       Your requirements could not be resolved to an installable set of packages.
       
         Problem 1
           - Installation request for erusev/parsedown 1.7.3 -> satisfiable by erusev/parsedown[1.7.3].
           - erusev/parsedown 1.7.3 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
         Problem 2
           - Installation request for laravel/framework v6.5.2 -> satisfiable by laravel/framework[v6.5.2].
           - laravel/framework v6.5.2 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
         Problem 3
           - laravel/framework v6.5.2 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
           - spatie/laravel-sluggable 2.2.1 requires illuminate/database ~5.6.0|~5.7.0|~5.8.0|^6.0 -> satisfiable by laravel/framework[v6.5.2].
           - Installation request for spatie/laravel-sluggable 2.2.1 -> satisfiable by spatie/laravel-sluggable[2.2.1].
```

I've ensured my version of herokuish (0.5.6) is up to date and I'm using the latest release of Dokku.

Can you advise any further debugging steps here? If this issue is unrelated to herokuish, apologies!

**Comment by danabrey** [comment] 2020-02-29 11:08
I've tried pinning to previous releases of the buildpack before this PR https://github.com/heroku/heroku-buildpack-php/issues/395

But no difference.

**Comment by nemanjan00** [comment] 2020-02-29 12:05
Looks to me like it is PHP version related, not buildpack version related. 

It looks it is a problem of missing system dependencies. 

Multipack with apt buildpack and php buildpack seems to be a solution... 

Add apt buildpack to you ``.buildpacks`` file:

```
https://github.com/heroku/heroku-buildpack-apt
https://github.com/heroku/heroku-buildpack-php#v171
```

Now, to define missing deps, create file ``Aptfile`` containing these 2 deps:

```
libonig-dev
libonig4
```

It should work after that.

**Comment by danabrey** [comment] 2020-02-29 15:34
Thanks @nemanjan00, I've given this a go. I changed to the two buildpacks:

```
# dokku buildpacks:list my_app
-----> my_app buildpack urls
       https://github.com/heroku/heroku-buildpack-apt
       https://github.com/heroku/heroku-buildpack-php#v171
```

And added the Aptfile:

```
libonig-dev
libonig4
```

But I still get the same result:

```
-----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
       Detected buildpacks: multi nodejs php
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-php
=====> Detected Framework: PHP
-----> Bootstrapping...
-----> Installing platform packages...
       - php (7.4.3)
       - ext-mbstring (bundled with php)
       - apache (2.4.41)
       - nginx (1.16.1)
PHP Warning:  PHP Startup: Unable to load dynamic library 'mbstring.so' (tried: /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so (libonig.so.4: cannot open shared object file: No such file or directory), /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so.so (/app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'mbstring.so' (tried: /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so (libonig.so.4: cannot open shared object file: No such file or directory), /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so.so (/app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

I am a bit suspicious that the `apt` buildpack isn't being downloaded before the php one - have I set that up wrong?

**Comment by danabrey** [comment] 2020-02-29 15:37
This PR seems to be relevant to the issue: https://github.com/heroku/heroku-buildpack-php/pull/394

But using this latest buildpack results in the same error.

**Comment by haggen** [comment] 2020-02-29 16:52
@danabrey 

> But I still get the same result:

Check if you have a `BUILDPACK_URL` set on dokku, cause it overrides the `.buildpacks` files config.

**Comment by danabrey** [comment] 2020-02-29 17:04
Agh, can't believe I missed that @haggen, thanks a lot. I had tried overriding the `BUILDPACK_URL` with a specific tagged release of the PHP buildpack earlier today!

Removed that config setting and the solution from @nemanjan00 works perfectly. Thanks both.

**Comment by sicutdeux** [comment] 2020-02-29 21:12
I think this should not be closed until this libs are included by default on herokuish, since this breaks normal installs for dokku.

**Comment by nemanjan00** [comment] 2020-03-02 12:09
To me, this sounds like just herokuish build is out of date

**Comment by mirkogeest** [comment] 2020-03-04 11:11
I had this same issue today, so I followed @nemanjan00 instructions:

- remove the BUILDPACK_URL env var at the server
- create .buildpack file with suggested content
- create Aptfile file with suggested content
- git add, git commit, git push to dokku server

But I get this error in the app logs:

> setuidgid: fatal: unable to run vendor/bin/heroku-php-nginx: file does not exist

I tried to add to Aptfile heroku-php-nginx, but got other errors.

Finally I removed the mbstring from composer.json and composer.lock, as the mbstring extension was only used at phpmailer library, and now I could deploy and run successfully.

**Comment by sicutdeux** [comment] 2020-03-04 16:18
Fixed my issues doing a mix of @nemanjan00 recipe, I have several builds using Dokku the most complex and probably will help @mirkogeest here it goes:

- Don't use BUILDPACK_URL env var, set the config using the `dokku buildpack:set` command:

` https://github.com/heroku/heroku-buildpack-apt,https://github.com/heroku/heroku-buildpack-php.git,https://github.com/heroku/heroku-buildpack-nodejs.git
`

- You can discard using the heroku-buildpack-nodejs if the project does not use it.

- Be careful with the order of buildpacks:
1. heroku-buildpack-apt (this will install the dependency)
2. heroku-buildpack-php (this will add the php and nginx/apache and use composer to download the rest of the dependencies)
3. heroku-buildpack-nodejs (this will use nodejs to handle the frontend build)

- Don't use the .buildpack since using the config on dokku.

- Created the Aptfile with this content:

```
libonig-dev
libonig4
```

This works for me since the first heroku-buildpack-apt uses apt to install the libraries from Aptfile, then, it detects is a PHP Applications and later it build the Frontend using NODEJS buildpack.

Hope this helps.

**Comment by sicutdeux** [comment] 2020-03-04 16:35
And like i have said before, the last release #533 does not fix the issue with latest heroku-buildpack-php https://github.com/heroku/heroku-buildpack-php/releases/tag/v172 the library is still missing.

**Comment by josegonzalez** [comment] 2020-03-05 07:21
Are the packages not included with herokuish 0.5.7?

**Comment by josegonzalez** [comment] 2020-03-05 07:25
A PR to add the packages [here](https://github.com/gliderlabs/herokuish/blob/master/Dockerfile#L6) would work. 

I would think the packages are available because of [this](https://github.com/heroku/stack-images/blob/df7cdc70854ea6bff3a3f1175524384cd9d6e9ed/heroku-18-build/installed-packages.txt#L336) but maybe there wasn't an updated cedar stack?

**Comment by sicutdeux** [comment] 2020-03-05 14:51
I  updated Dokku from apt before doing the fix i commented above, so i  think those packages where not included.

**Comment by scasei** [comment] 2020-03-05 15:11
@josegonzalez Thanks for reopenning this bug. Dont know whats wrong here, the docker images are from 20.02 (https://hub.docker.com/r/heroku/heroku/tags) and the related heroku-stack-image commit is from 31.01 (https://github.com/heroku/stack-images/commit/df7cdc70854ea6bff3a3f1175524384cd9d6e9ed)

So it would be great to have the Dockerfile changed as workaround?

**Comment by scasei** [comment] 2020-03-05 15:14
Here is a PR:
https://github.com/gliderlabs/herokuish/pull/534

**Comment by scasei** [comment] 2020-03-05 15:22
@josegonzalez Antoher hint: can somebody update the latest tag on docker hub? 
https://hub.docker.com/r/gliderlabs/herokuish/tags

**Comment by josegonzalez** [comment] 2020-03-06 14:46
I just ran the following:


```
$ docker run -it gliderlabs/herokuish:v0.5.7 apt list --installed | grep onig
libonig-dev/now 6.7.0-1 amd64 [installed,local]
libonig4/now 6.7.0-1 amd64 [installed,local]
```

Seems like 0.5.7 should work fine?

Oh, heh. I didn't make the deb package release... I'll do that now.

**Comment by josegonzalez** [comment] 2020-03-06 14:48
Can folks try out 0.5.7?

If this works, I'll make sure we get deb releases into the herokuish release pipeline.

**Comment by nemanjan00** [comment] 2020-03-06 14:55
Sure, will test it right now.

**Comment by nemanjan00** [comment] 2020-03-06 15:05
I can confirm I was able to build my app, without any problems, and without Aptfile

**Comment by josegonzalez** [comment] 2020-03-06 15:05
Great! Closing.

**Closed by josegonzalez** 2020-03-06 15:05 UTC

**Comment by scasei** [comment] 2020-03-06 15:08
My gitlab ci still dies at building stage :(

**Comment by scasei** [comment] 2020-03-06 15:09
I really think the tag 'latest' has to be updated on docker hub: https://hub.docker.com/r/gliderlabs/herokuish/tags

**Comment by nemanjan00** [comment] 2020-03-06 15:15
0.5.7 is ok, and latest is not

**Comment by scasei** [comment] 2020-03-06 15:18
@nemanjan00 And latest should be equal to 0.5.7 or do i miss something?

**Comment by nemanjan00** [comment] 2020-03-06 15:20
Latest is quite weird concept. 

In this case, master tag seems to be the latest tag

**Comment by scasei** [comment] 2020-03-06 15:29
I'm with you, but my gitlab loads the latest tag in autodevops, so without hacking deep and change everything, it would be cool if somebody with access to docker hub could update the latest tag please or is this so complicated eg more than 2 commands?

**Comment by josegonzalez** [comment] 2020-03-06 15:59
Pushed.

**Comment by scasei** [comment] 2020-03-06 16:08
@josegonzalez Really great, thank you, works like a charm!

**Comment by josegonzalez** [comment] 2020-03-06 16:56
Feel free to donate to the dokku patreon or opencollective to support further fixes on these sorts of projects.

https://patreon.com/dokku
https://opencollective.com/dokku

**Comment by Neamar** [comment] 2020-03-12 19:41
FWIW, anyone with the problem can just pull latest herokuish, no need to use the apt buildpack anymore:

```
docker rmi gliderlabs/herokuish:latest --force
docker pull gliderlabs/herokuish:latest
```
